version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_network

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - internal_network

  web:
    build: .
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/my_app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379/0
    env_file:
      - .env
    networks:
      - internal_network
    tty: true
    stdin_open: true

  sidekiq:
    build: .
    command: bash -c "bundle exec sidekiq"
    volumes:
      - .:/my_app
    depends_on:
      - redis
      - db
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    env_file:
      - .env
    networks:
      - internal_network
    tty: true
    stdin_open: true
    restart: on-failure

volumes:
  postgres_data:
  redis_data:

networks:
  internal_network:
    driver: bridge
